version: "3.7"
services:
  nuxeo:
    build: ./nuxeo_image/
    ports:
      - "8080:8080"
    environment:
      NUXEO_PACKAGES: "nuxeo-web-ui /tmp/amazon-s3-online-storage-1.9.6.zip"
      NUXEO_DB_TYPE: postgresql
      NUXEO_DB_HOST: postgres
      JAVA_OPTS: "-Djsse.enableSNIExtension=false -Dcom.amazonaws.sdk.disableCertChecking -Dcom.sun.jndi.ldap.connect.pool.protocol=plain"
    depends_on:
      - elasticsearch1
    restart: always

  localstack:
    image: localstack/localstack
    ports:
      - "4567-4596:4567-4596"
    environment:
      - SERVICES=es,s3
      - DEFAULT_REGION=us-west-2
      - HOSTNAME=localstack


  ad-mock:
    image: rroemhild/test-openldap
    ports:
      - "389:389"
      - "636:636"


  postgres:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nuxeo
      POSTGRES_PASSWORD: nuxeo
      POSTGRES_DB: nuxeo
#
  elasticsearch1:
    image: elasticsearch:6.8.5
    environment:
      discovery.type: "single-node"
      xpack.security.enabled: "false"
      cluster.name: "nuxeoCluster"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9300:9300"
      - "9200:9200"